Algoritmo "Antecessor"
// Disciplina   : Lógica de programação com JavaScript
// Professor   : Jailson
// Descrição   : Subtrai um do valor armazenado na variável num
// Autor(a)    : Felipe Barros
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
numero,valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Aperte uma tecla: ")
leia(numero)
valor <- numero-1
escreva("O antecedente desse número é: ",valor)

Fimalgoritmo