Algoritmo "Sucessor"
// Disciplina  : Lógica de programação com JavaScript
// Professor   : Jailson
// Descrição   : Soma mais um no valor armazenado na variável num
// Autor(a)    : Felipe Barros
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
numero:inteiro
sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero)
sucessor <- numero+1
escreva("O sucessor desse número é: ",sucessor)

Fimalgoritmo