Algoritmo "Área do círculo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Felipe Barros
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
raio,area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual o raio do seu círculo?")
leia(raio)
area <- pi*raio^2
escreval("A área do seu círculo é: ",area:2:2)
Fimalgoritmo